### ISSUE TITLE
 No implementation found for native Ljssc/SerialNativeInterface;.openPort:

### ISSUE THREAD

**Issue by shishuyao** [scream3r/java-simple-serial-connector#94]
hello!
when i import 2.8.0 jssc.jar into my android studio and run my project,it's crashed:
`09-22 15:06:30.801 4944-4944/zkh.com.serialporttest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      java.lang.UnsatisfiedLinkError: Native method not found: jssc.SerialNativeInterface.openPort:(Ljava/lang/String;Z)J
                                                                          at jssc.SerialNativeInterface.openPort(Native Method)
                                                                          at jssc.SerialPort.openPort(SerialPort.java:158)
                                                                          at zkh.com.serialporttest.MainActivity.sendSerialCMD(MainActivity.java:171)
                                                                          at zkh.com.serialporttest.MainActivity.onClick(MainActivity.java:87)
                                                                          at android.view.View.performClick(View.java:4204)
                                                                          at android.view.View$PerformClick.run(View.java:17355)
                                                                          at android.os.Handler.handleCallback(Handler.java:725)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                          at dalvik.system.NativeStart.main(Native Method)`

i use it like this:
`   SerialPort port = new SerialPort(serialModel.getSerialPort());
            if (port != null && !port.isOpened()) {
                try {
                    port.openPort();
                } catch (SerialPortException e) {
                    e.printStackTrace();
                }
            }`

**Comment by wintersun** [comment]
I have the same problem and I found an article show how to fix it: http://www.jianshu.com/p/fa7533e10cf9
I followed the steps but failed, can you try it?

**Comment by shishuyao** [comment]
这个问题解决了，建议你参阅下我的博客：
www.shishuyao.com 有一篇关于Serial调试的。

I have solved this problem already，please refer to my blog:
www.shishuyao.com

**Comment by nsiatras** [comment]
Hello,

I am trying to do the same thing here but without any luck
I get the same exception when I try to get a serial ports list.
Reading your blog I couldn't understand much... Is there any help in English ?

Thank you for any replies :)
